// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Coffee.Data.Migrations
{
    [DbContext(typeof(CoffeeContext))]
    [Migration("20221205112942_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("Coffee.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageName")
                        .HasColumnType("TEXT")
                        .HasColumnName("ImageFileName");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Black Coffee dapat membantu meningkatkan daya ingat.",
                            ImageName = "1.jpg",
                            Name = "Black Coffee",
                            Price = 40.000m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Latte sangat baik dalam mengelola diabetes tipe-2.",
                            ImageName = "2.jpg",
                            Name = "Coffee Latte",
                            Price = 50.000m
                        },
                        new
                        {
                            Id = 3,
                            Description = "cappucino dapat membantu mengatasi kolesterol dan mencegah beberapa masalah yang berhubungan dengan jantung. ",
                            ImageName = "3.jpeg",
                            Name = "Coffee Cappucino",
                            Price = 60.000m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Coffee yang dapat membantu melawan depresi",
                            ImageName = "4.jpg",
                            Name = "Americano Coffee",
                            Price = 60.000m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Coffee yand dapat Mengurangi risiko stroke",
                            ImageName = "5.jpg",
                            Name = "Espresso Coffee",
                            Price = 54.000m
                        },
                        new
                        {
                            Id = 6,
                            Description = " Coffee yang dapat merontokan lemak secara alami.",
                            ImageName = "6.jpg",
                            Name = "Mocha Coffee",
                            Price = 75.000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
